
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/hpc_software/tools/cmake/3.26.0/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.15.47+prerelease70 - x86_64
...
